/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.finalOdev;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class adisyon extends javax.swing.JPanel {

    /**
     * Creates new form masalar
     */
    public adisyon(int tableId, DataBase data) {
        this.data = data;
        localID = tableId;
        initComponents();
        loadItem();
    }

    private void tableSetModel() {
        itemTable.setModel(new DefaultTableModel(new Object[][]{},
                new String[]{
                    "ÜRÜN İSMİ", "MİKTAR", "FİYAT"
                }));
        model = (DefaultTableModel) itemTable.getModel();
    }

    private void loadItem() {

        itemlist = data.getOrderItems(localID);
        tableSetModel();
        page2MainScrollList.removeAll();

        for (int i = 0; i < itemlist.length; i++) {

            itemJPanel items = new itemJPanel(itemTable, hesap, itemlist[i].id, itemlist[i].name, itemlist[i].payed, itemlist[i].quantity, itemlist[i].price, payitemlist);

            if (i % 2 == 0) {
                items.setBackground(Color.DARK_GRAY);
            } else {
                items.setBackground(Color.GRAY);

            }

            page2MainScrollList.add(items);

        }
        page2MainScrollList.revalidate();
        page2MainScrollList.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page2Header = new javax.swing.JPanel();
        page2HeaderLabel = new javax.swing.JLabel();
        page2HeaderLabel2 = new javax.swing.JLabel();
        page2HeaderButton = new javax.swing.JButton();
        page2Main = new javax.swing.JPanel();
        page2MainPrice = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        selectall = new javax.swing.JButton();
        hesap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        payment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        page2MainScroll = new javax.swing.JScrollPane();
        page2MainScrollList = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1000, 500));

        page2Header.setBackground(new java.awt.Color(0, 102, 102));
        page2Header.setMaximumSize(new java.awt.Dimension(32767, 40));
        page2Header.setMinimumSize(new java.awt.Dimension(0, 40));
        page2Header.setPreferredSize(new java.awt.Dimension(1000, 40));

        page2HeaderLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        page2HeaderLabel.setText("Adisyon");

        page2HeaderLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        page2HeaderLabel2.setText("masa:");

        page2HeaderButton.setText("↻");
        page2HeaderButton.setMaximumSize(new java.awt.Dimension(38, 38));
        page2HeaderButton.setMinimumSize(new java.awt.Dimension(38, 38));
        page2HeaderButton.setPreferredSize(new java.awt.Dimension(38, 38));
        page2HeaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page2HeaderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout page2HeaderLayout = new javax.swing.GroupLayout(page2Header);
        page2Header.setLayout(page2HeaderLayout);
        page2HeaderLayout.setHorizontalGroup(
            page2HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page2HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(page2HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(page2HeaderLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                .addComponent(page2HeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        page2HeaderLayout.setVerticalGroup(
            page2HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page2HeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(page2HeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(page2HeaderLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        page2Main.setBackground(new java.awt.Color(102, 255, 102));

        page2MainPrice.setBackground(new java.awt.Color(0, 204, 255));

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ÜRÜN İSMİ", "MİKTAR", "FİYAT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(itemTable);

        selectall.setText("TÜMÜNÜ SEÇ");
        selectall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectallActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TOPLAM FİYAT");

        payment.setText("ÖDEME");
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });

        jButton1.setText("adisyonu kapat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("İPTAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout page2MainPriceLayout = new javax.swing.GroupLayout(page2MainPrice);
        page2MainPrice.setLayout(page2MainPriceLayout);
        page2MainPriceLayout.setHorizontalGroup(
            page2MainPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(page2MainPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(page2MainPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(page2MainPriceLayout.createSequentialGroup()
                        .addGroup(page2MainPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectall, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(page2MainPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hesap)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        page2MainPriceLayout.setVerticalGroup(
            page2MainPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page2MainPriceLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(page2MainPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(page2MainPriceLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hesap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(page2MainPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectall, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(payment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        page2MainScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        page2MainScrollList.setBackground(new java.awt.Color(172, 160, 20));
        page2MainScrollList.setLayout(new javax.swing.BoxLayout(page2MainScrollList, javax.swing.BoxLayout.PAGE_AXIS));
        page2MainScroll.setViewportView(page2MainScrollList);

        javax.swing.GroupLayout page2MainLayout = new javax.swing.GroupLayout(page2Main);
        page2Main.setLayout(page2MainLayout);
        page2MainLayout.setHorizontalGroup(
            page2MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page2MainLayout.createSequentialGroup()
                .addComponent(page2MainScroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(page2MainPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        page2MainLayout.setVerticalGroup(
            page2MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page2MainScroll)
            .addComponent(page2MainPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page2Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(page2Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(page2Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(page2Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void page2HeaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page2HeaderButtonActionPerformed
        // TODO add your handling code here:
        payitemlist.clear();
        loadItem();
        repaint();
    }//GEN-LAST:event_page2HeaderButtonActionPerformed

    private void selectallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectallActionPerformed
        // TODO add your handling code here:
        tableSetModel();
        Object[] row = new Object[3];
        for (itemProduct item : itemlist) {
            boolean found = false;
            if (item.quantity > item.payed) {
                itemProduct newItem = new itemProduct();
                newItem.id = item.id;
                newItem.payed = item.quantity;
                payitemlist.add(newItem);
                

                for (int j = 0; j < itemTable.getModel().getRowCount(); j++) {

                    if (item.name.equals(itemTable.getModel().getValueAt(j, 0))) {
                      
                        int currentCount = (int) itemTable.getModel().getValueAt(j, 1);
                        itemTable.getModel().setValueAt(currentCount + item.quantity - item.payed, j, 1);

                        found = true;
                    }
                }
                if (!found) {
                    row[0] = item.name;
                    row[1] = item.quantity - item.payed;
                    row[2] = item.price;

                    model.addRow(row);
                    itemTable.setModel(model);
                }
                float sum = 0;
                for (int j = 0; j < itemTable.getModel().getRowCount(); j++) {
                    sum += (int) itemTable.getModel().getValueAt(j, 1) * (float) itemTable.getModel().getValueAt(j, 2);

                }
                hesap.setText(String.valueOf(sum));
            }
        }


    }//GEN-LAST:event_selectallActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
        data.pay(payitemlist);
        loadItem();
        hesap.setText("");

    }//GEN-LAST:event_paymentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:adisyon kapat
        if (data.payed(localID)) {
            data.closeAdisyon(localID);
            JOptionPane.showMessageDialog(this, "Adisyon başarıyla kapatıldı.");
            loadItem();

        } else {
            int result = JOptionPane.showConfirmDialog(
                    this,
                    "Adisyon henüz ödenmedi. Yine de kapatılsın mı?",
                    "Ödeme Onayı",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (result == JOptionPane.YES_OPTION) {
                data.closeAdisyon(localID);
            } 
            loadItem();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        payitemlist.clear();
        loadItem();
        repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private DefaultTableModel model;
    itemProduct itemlist[] = null;
    DataBase data;
    private ArrayList<itemProduct> payitemlist = new ArrayList<>();
    private int localID;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hesap;
    private javax.swing.JTable itemTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel page2Header;
    private javax.swing.JButton page2HeaderButton;
    private javax.swing.JLabel page2HeaderLabel;
    private javax.swing.JLabel page2HeaderLabel2;
    private javax.swing.JPanel page2Main;
    private javax.swing.JPanel page2MainPrice;
    private javax.swing.JScrollPane page2MainScroll;
    private javax.swing.JPanel page2MainScrollList;
    private javax.swing.JButton payment;
    private javax.swing.JButton selectall;
    // End of variables declaration//GEN-END:variables
}
