/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.finalOdev;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class itemJPanel extends javax.swing.JPanel {

    private void listele() {
        boolean found = false;

        for (itemProduct item : payitemlist) {
            if (item.id == id) {
                item.payed++;
                found = true;
                System.out.println("Ürün güncellendi.");
                break;
            }
        }

        if (!found) {
            itemProduct newItem = new itemProduct();
            newItem.id = id;
            newItem.payed = payed;
            payitemlist.add(newItem);
        }
    }

    private boolean payed() {
        for (itemProduct item : payitemlist) {
            System.out.println(payed);
            if (item.id == id && item.payed >= quantity) {

                System.out.println("com.example.finalOdev.itemJPanel.payed()2");

                return false;

            }
        }
        if (payed >= quantity) {
            return false;

        }
        return true;
    }

    /**
     * Creates new form itemJPanel
     *
     * @param table
     * @param total
     * @param id
     * @param name
     * @param payed
     * @param quantity
     * @param price
     * @param payitemlist
     */
    public itemJPanel(javax.swing.JTable table, javax.swing.JTextField total, int id, String name, int payed, int quantity, float price, ArrayList<itemProduct> payitemlist) {
        this.payitemlist = payitemlist;
        itemTable = table;
        this.id = id;
        this.total = total;
        this.price = price;
        this.quantity = quantity;
        this.payed = payed;
        this.name = name;
        initComponents();
        itemPrice1.setText(String.valueOf(this.price) + "TL");
        itemName1.setText(name);
        itemCount1.setText(payed + "/" + quantity + " ");
        model = (DefaultTableModel) itemTable.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemName1 = new javax.swing.JLabel();
        itemPrice1 = new javax.swing.JLabel();
        itemCount1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(2147483647, 70));
        setMinimumSize(new java.awt.Dimension(175, 70));
        setPreferredSize(new java.awt.Dimension(200, 70));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout(20, 0));

        itemName1.setBackground(new java.awt.Color(51, 51, 0));
        itemName1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        itemName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemName1.setText(" Çay");
        itemName1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        itemName1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(itemName1, java.awt.BorderLayout.LINE_START);

        itemPrice1.setBackground(new java.awt.Color(0, 51, 51));
        itemPrice1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        itemPrice1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        itemPrice1.setText("15 TL");
        add(itemPrice1, java.awt.BorderLayout.CENTER);

        itemCount1.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        itemCount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCount1.setText("3/8 ");
        add(itemCount1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        boolean find = false;
        Object[] row = new Object[3];

        System.out.println(".mouseClicked()1");
        if (payed()) {
            for (int j = 0; j < itemTable.getModel().getRowCount(); j++) {

                System.out.println(".mouseClicked()2");

                if (name.equals(itemTable.getModel().getValueAt(j, 0))) {
                    System.out.println(".mouseClicked()3");
                    int currentCount = (int) itemTable.getModel().getValueAt(j, 1);
                    itemTable.getModel().setValueAt(currentCount + 1, j, 1);
                    payed++;
                    listele();
                    find = true;
                } else {
                    System.out.println((String) itemTable.getModel().getValueAt(j, 0) + name);

                }
            }
            System.out.println(".mouseClicked()4");
            if (!find) {
                row[0] = name;
                row[1] = 1;
                row[2] = price;
                payed++;
                listele();
                model.addRow(row);
                itemTable.setModel(model);
            }
            float sum = 0;
            for (int j = 0; j < itemTable.getModel().getRowCount(); j++) {
                sum += (int) itemTable.getModel().getValueAt(j, 1) * (float) itemTable.getModel().getValueAt(j, 2);

            }
            total.setText(String.valueOf(sum));
        }

    }//GEN-LAST:event_formMouseClicked

    //private itemProduct[] itemlist;
    private ArrayList<itemProduct> payitemlist;

    private int id;
    private javax.swing.JTextField total;
    private DefaultTableModel model;
    private String name;
    private int payed;
    private int quantity;
    private float price;
    private javax.swing.JTable itemTable;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemCount1;
    private javax.swing.JLabel itemName1;
    private javax.swing.JLabel itemPrice1;
    // End of variables declaration//GEN-END:variables
}
