/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.finalOdev;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class itemAddPage extends javax.swing.JPanel {

    /**
     * Creates new form itemAddPage
     */
    public itemAddPage(DataBase data) {
        this.data = data;
        initComponents();
        reload();

    }

    private void reload() {
        data.showItems(itemTable);
        data.showType(typeTable);
        data.getType(typeList);  //liste güncelleniyor
        ComboBoxModel<String> model = new DefaultComboBoxModel<>(); //typeBox adlı ComboBox’a bu boş model atanarak eski veriler temizleniyor.
        typeBox.setModel(model);
        for (typeProduct type : typeList) {
            typeBox.addItem(type.name);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page2Header = new javax.swing.JPanel();
        page2HeaderLabel = new javax.swing.JLabel();
        page2HeaderLabel2 = new javax.swing.JLabel();
        page2HeaderButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        urun_ismi = new javax.swing.JTextField();
        urun_fiyati = new javax.swing.JTextField();
        ekle = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        typeTable = new javax.swing.JTable();
        typeDelButton = new javax.swing.JButton();
        TypeField = new javax.swing.JTextField();
        typeAddButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        page2Header.setBackground(new java.awt.Color(0, 102, 102));
        page2Header.setMaximumSize(new java.awt.Dimension(32767, 40));
        page2Header.setMinimumSize(new java.awt.Dimension(0, 40));
        page2Header.setPreferredSize(new java.awt.Dimension(1580, 40));

        page2HeaderLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        page2HeaderLabel.setText("Adisyon");

        page2HeaderLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        page2HeaderLabel2.setText("masa:");

        page2HeaderButton.setText("↻");
        page2HeaderButton.setMaximumSize(new java.awt.Dimension(38, 38));
        page2HeaderButton.setMinimumSize(new java.awt.Dimension(38, 38));
        page2HeaderButton.setPreferredSize(new java.awt.Dimension(38, 38));
        page2HeaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page2HeaderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout page2HeaderLayout = new javax.swing.GroupLayout(page2Header);
        page2Header.setLayout(page2HeaderLayout);
        page2HeaderLayout.setHorizontalGroup(
            page2HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page2HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(page2HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(page2HeaderLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addGap(375, 375, 375)
                .addComponent(page2HeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        page2HeaderLayout.setVerticalGroup(
            page2HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page2HeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(page2HeaderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(page2HeaderLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(56, 13, 202));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("YENİ ÜRÜN ADI:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("YENİ ÜRÜN FİYAT:");

        urun_fiyati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_fiyatiActionPerformed(evt);
            }
        });

        ekle.setText("EKLE");
        ekle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("YENİ ÜRÜN EKLEME");

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "urun_ıd", "urun_ismi", "urun_fiyat"
            }
        ));
        jScrollPane1.setViewportView(itemTable);

        jButton2.setText("SİL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("KATEGORİ:");

        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane2.setMinimumSize(new java.awt.Dimension(150, 20));

        typeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        typeTable.setMinimumSize(new java.awt.Dimension(150, 80));
        jScrollPane2.setViewportView(typeTable);

        typeDelButton.setText("SİL");
        typeDelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeDelButtonActionPerformed(evt);
            }
        });

        typeAddButton.setText("EKLE");
        typeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeAddButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("KATEGORİ ADI:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urun_fiyati)
                            .addComponent(urun_ismi)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TypeField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(typeBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(typeDelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urun_ismi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(urun_fiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(typeAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeDelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(page2Header, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(page2Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int seciliSatir = itemTable.getSelectedRow();// ürün silme 

        if (seciliSatir >= 0) {//Kullanıcının bir satır seçip seçmediği kontrol edilir.
            int urunId = (int) itemTable.getValueAt(seciliSatir, 0); // id sütunu 0. sütun olmalı
            data.delItem(urunId);
            data.showItems(itemTable); // tabloyu güncelle
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen silinecek bir ürün seçin.");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        if (urun_ismi.getText().equals("") || urun_fiyati.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "hatalı giriş.");
        } else {

            int typeId = 1;
            for (typeProduct type : typeList) {
                if (type.name.equals(typeBox.getSelectedItem().toString())) {
                    typeId = type.id;
                    System.out.println(typeId);
                }
            }
            data.newItem(urun_ismi.getText(), urun_fiyati.getText(), typeId);

        }
        reload();
    }//GEN-LAST:event_ekleActionPerformed

    private void urun_fiyatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_fiyatiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urun_fiyatiActionPerformed

    private void page2HeaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page2HeaderButtonActionPerformed
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_page2HeaderButtonActionPerformed

    private void typeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeAddButtonActionPerformed
        // TODO add your handling code here:
        if (TypeField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "hatalı giriş.");

        } else {
            data.newType(TypeField.getText()); // ürün türü
        }
        reload();
    }//GEN-LAST:event_typeAddButtonActionPerformed

    private void typeDelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeDelButtonActionPerformed
        // TODO add your handling code here:
        int seciliSatir = itemTable.getSelectedRow();
        if (seciliSatir >= 0) {
            int urunId = (int) typeTable.getValueAt(seciliSatir, 0);
            data.delType(urunId);
            reload(); // tabloyu güncelle
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen silinecek bir ürün seçin.");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_typeDelButtonActionPerformed

    DataBase data;
    List<typeProduct> typeList = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TypeField;
    private javax.swing.JButton ekle;
    private javax.swing.JTable itemTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel page2Header;
    private javax.swing.JButton page2HeaderButton;
    private javax.swing.JLabel page2HeaderLabel;
    private javax.swing.JLabel page2HeaderLabel2;
    private javax.swing.JButton typeAddButton;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JButton typeDelButton;
    private javax.swing.JTable typeTable;
    private javax.swing.JTextField urun_fiyati;
    private javax.swing.JTextField urun_ismi;
    // End of variables declaration//GEN-END:variables
}
