/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.finalOdev;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        super.setVisible(true);
    }

    public class ImagePanel extends JPanel {

        private final Image backgroundImage;

        public ImagePanel(String imagePath) {
            backgroundImage = new ImageIcon(imagePath).getImage();
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new ImagePanel("C:\\Users\\hp\\Desktop\\yakup\\code\\Java Project\\finalOdev\\app\\src\\main\\resources\\wp14864604.png");
        LabelKullaniciAdi = new javax.swing.JLabel();
        TextFieldKullaniciAdi = new javax.swing.JTextField();
        LabelSifre = new javax.swing.JLabel();
        TextFieldSifre = new javax.swing.JPasswordField();
        ButtonLogin = new javax.swing.JButton();
        LabelUnuttum = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextFieldId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LabelKullaniciAdi.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        LabelKullaniciAdi.setText("Kullanıcı Adı:");

        TextFieldKullaniciAdi.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        TextFieldKullaniciAdi.setText("yakupkafe");

        LabelSifre.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        LabelSifre.setText("Şifre:");

        TextFieldSifre.setText("yakup123");

        ButtonLogin.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        ButtonLogin.setText("Giriş Yap");
        ButtonLogin.setBorder(new javax.swing.border.MatteBorder(null));
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });

        LabelUnuttum.setForeground(new java.awt.Color(0, 102, 204));
        LabelUnuttum.setText("Şifreyi Unuttum...");
        LabelUnuttum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelUnuttum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelUnuttumMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(153, 0, 0));

        TextFieldId.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        TextFieldId.setText("1");

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel1.setText("İd:");

        LabelError.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldId)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 108, Short.MAX_VALUE)
                        .addComponent(LabelUnuttum))
                    .addComponent(ButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldSifre)
                    .addComponent(LabelSifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldKullaniciAdi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelKullaniciAdi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelKullaniciAdi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelSifre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelUnuttum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelUnuttumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelUnuttumMouseClicked
        System.out.println("com.example.finalOdev.Login.jLabel3MouseClicked()");
    }//GEN-LAST:event_LabelUnuttumMouseClicked

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        if (TextFieldId.getText().equals("") || TextFieldKullaniciAdi.getText().equals("") || TextFieldSifre.getText().equals("")) {
            LabelError.setText("Hatalı giriş");
        } else {
            user.id = Integer.valueOf(TextFieldId.getText());
            user.username = TextFieldKullaniciAdi.getText();
            user.password = TextFieldSifre.getText();
            DataBase data = new DataBase();
            if (data.connect(user)) {
                main main = new main(data);
                super.setVisible(false);
            } else {
                LabelError.setText("Hatalı giriş");
            }
        }

    }//GEN-LAST:event_ButtonLoginActionPerformed

    public userProduct user = new userProduct();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JLabel LabelError;
    private javax.swing.JLabel LabelKullaniciAdi;
    private javax.swing.JLabel LabelSifre;
    private javax.swing.JLabel LabelUnuttum;
    private javax.swing.JTextField TextFieldId;
    private javax.swing.JTextField TextFieldKullaniciAdi;
    private javax.swing.JTextField TextFieldSifre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
