package com.example.finalOdev;

import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main(DataBase data) {
        this.data = data;
        initComponents();
        super.setVisible(true);
        tablepage = new tablePage(pages,data);
        showPage(tablepage);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        sideBarButton1 = new javax.swing.JButton();
        sideBarButton2 = new javax.swing.JButton();
        sideBarbutton3 = new javax.swing.JButton();
        sideBarButtonEnd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pages = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        sideBar.setBackground(new java.awt.Color(0, 51, 51));
        sideBar.setMinimumSize(new java.awt.Dimension(300, 300));

        sideBarButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sideBarButton1.setText("Masalar");
        sideBarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideBarButton1ActionPerformed(evt);
            }
        });

        sideBarButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sideBarButton2.setText("Adisyon");
        sideBarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideBarButton2ActionPerformed(evt);
            }
        });

        sideBarbutton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sideBarbutton3.setText("Ürün Ekleme");
        sideBarbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideBarbutton3ActionPerformed(evt);
            }
        });

        sideBarButtonEnd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sideBarButtonEnd.setText("Çıkış");
        sideBarButtonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideBarButtonEndActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Kullanıcı Ekleme");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideBarbutton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(sideBarButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sideBarButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sideBarButtonEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideBarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBarbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                .addComponent(sideBarButtonEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pages.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pages.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pages, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pages))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPage(JPanel panel) {
        pages.removeAll();

        pages.add(panel);
        pages.revalidate();
        pages.repaint();
    }


    private void sideBarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBarButton1ActionPerformed
        // TODO add your handling code here:
        showPage(tablepage);

    }//GEN-LAST:event_sideBarButton1ActionPerformed

    private void sideBarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBarButton2ActionPerformed
        // TODO add your handling code here:
        showPage(new adisyon(0,data));
    }//GEN-LAST:event_sideBarButton2ActionPerformed

    private void sideBarbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBarbutton3ActionPerformed
        showPage(new itemAddPage(data));
        repaint();
    }//GEN-LAST:event_sideBarbutton3ActionPerformed

    private void sideBarButtonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideBarButtonEndActionPerformed
System.exit(0);
    }//GEN-LAST:event_sideBarButtonEndActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showPage(new userAddPage(data));


    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        tablepage.updateLayout();
    }//GEN-LAST:event_formComponentResized

    DataBase data;
    private tablePage tablepage;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane pages;
    private javax.swing.JPanel sideBar;
    private javax.swing.JButton sideBarButton1;
    private javax.swing.JButton sideBarButton2;
    private javax.swing.JButton sideBarButtonEnd;
    private javax.swing.JButton sideBarbutton3;
    // End of variables declaration//GEN-END:variables
}
