/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.finalOdev;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class tablePage extends javax.swing.JPanel {

    public void updateLayout() {
        int width = page1Scroll.getWidth();

        for (int i = page1ScrollGrid.getComponentCount(); i < (page1Scroll.getWidth() / 160) * (page1Scroll.getHeight() / 160); i++) {

            JPanel panel = new JPanel();
            panel.setVisible(false);
            panel.setPreferredSize(new Dimension(150, 150));
            page1ScrollGrid.add(panel);
        }

        int columns = Math.max(1, width / (170));
        page1ScrollGrid.setLayout(new GridLayout(0, columns, 10, 10));
        page1ScrollGrid.revalidate();
    }

    /**
     * Creates new form tablePage
     */
    public void loadTables() {

        page1ScrollGrid.removeAll();
        page1ScrollGrid.setLayout(new GridLayout());

        
        tableProduct[] table = data.getTables();
        for (int j = 0; j < table.length; j++) {
            adisyon adisyon = new adisyon(table[j].id,data);
            tableJPanel tables = new tableJPanel(table[j].name, table[j].free, table[j].price);
            tables.setSize(new Dimension(150, 150));
            tables.addMouseListener(new MouseListener() {

                @Override
                public void mouseClicked(MouseEvent e) {
                    menu.removeAll();
                    menu.add(adisyon);
                    menu.revalidate();
                    menu.repaint();
                }

                @Override
                public void mousePressed(MouseEvent e) {

                }

                @Override
                public void mouseReleased(MouseEvent e) {

                }

                @Override
                public void mouseEntered(MouseEvent e) {

                }

                @Override
                public void mouseExited(MouseEvent e) {

                }
            });
            
            page1ScrollGrid.add(tables);
        }
        page1ScrollGrid.add(new tableAddJPanel(this,data));

        page1ScrollGrid.revalidate();
        page1ScrollGrid.repaint();

    }

    public tablePage(javax.swing.JLayeredPane menu, DataBase data) {
        this.data = data;
        this.menu = menu;
        initComponents();
        loadTables();
        updateLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page1Header = new javax.swing.JPanel();
        page1HeaderButton = new javax.swing.JButton();
        page1HeaderLabel = new javax.swing.JLabel();
        page1Scroll = new javax.swing.JScrollPane();
        page1ScrollGrid = new javax.swing.JPanel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        page1Header.setBackground(new java.awt.Color(0, 102, 102));

        page1HeaderButton.setText("↻");
        page1HeaderButton.setMaximumSize(new java.awt.Dimension(38, 38));
        page1HeaderButton.setMinimumSize(new java.awt.Dimension(38, 38));
        page1HeaderButton.setPreferredSize(new java.awt.Dimension(38, 38));
        page1HeaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page1HeaderButtonActionPerformed(evt);
            }
        });

        page1HeaderLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        page1HeaderLabel.setText("Masalar");

        javax.swing.GroupLayout page1HeaderLayout = new javax.swing.GroupLayout(page1Header);
        page1Header.setLayout(page1HeaderLayout);
        page1HeaderLayout.setHorizontalGroup(
            page1HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page1HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(page1HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(page1HeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        page1HeaderLayout.setVerticalGroup(
            page1HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page1HeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(page1HeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        page1Scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        page1Scroll.setPreferredSize(new java.awt.Dimension(1514, 900));

        page1ScrollGrid.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout page1ScrollGridLayout = new javax.swing.GroupLayout(page1ScrollGrid);
        page1ScrollGrid.setLayout(page1ScrollGridLayout);
        page1ScrollGridLayout.setHorizontalGroup(
            page1ScrollGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1712, Short.MAX_VALUE)
        );
        page1ScrollGridLayout.setVerticalGroup(
            page1ScrollGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );

        page1Scroll.setViewportView(page1ScrollGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page1Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(page1Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(page1Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(page1Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void page1HeaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page1HeaderButtonActionPerformed
        loadTables();
        updateLayout();
    }//GEN-LAST:event_page1HeaderButtonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        updateLayout();
    }//GEN-LAST:event_formComponentResized
    DataBase data;

    private javax.swing.JLayeredPane menu;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel page1Header;
    private javax.swing.JButton page1HeaderButton;
    private javax.swing.JLabel page1HeaderLabel;
    private javax.swing.JScrollPane page1Scroll;
    private javax.swing.JPanel page1ScrollGrid;
    // End of variables declaration//GEN-END:variables
}
